# Generated by Django 5.1.7 on 2025-04-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_entry_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('travel', 'Travel'), ('bills', 'Bills'), ('health', 'Health'), ('salary', 'Salary'), ('revenue', 'Revenue'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('transportation', 'Transportation'), ('housing', 'Housing'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('savings', 'Savings'), ('investments', 'Investments'), ('gifts', 'Gifts'), ('charity', 'Charity'), ('vacation', 'Vacation'), ('pets', 'Pets'), ('clothing', 'Clothing'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
