# Generated by Django 5.1.7 on 2025-04-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_entry_category_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='notes',
        ),
    ]
