# Generated by Django 5.1.7 on 2025-04-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('travel', 'Travel'), ('bills', 'Bills'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
